name: Build
on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      test_release:
        description: 'Test release?'
        required: true
        default: 'false'

jobs:
  build-ios:
    name: Jitterbug
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          xcodebuild archive -archivePath Jitterbug -scheme Jitterbug -configuration Release CODE_SIGNING_ALLOWED=NO
          codesign --force --sign - --timestamp=none --preserve-metadata=identifier,entitlements,flags "Jitterbug.xcarchive/Products/Applications/Jitterbug.app/PlugIns/OpenSSL.framework"
          codesign --force --sign - --timestamp=none --preserve-metadata=identifier,entitlements,flags "Jitterbug.xcarchive/Products/Applications/Jitterbug.app/Frameworks/OpenSSL.framework"
          codesign --force --sign - --entitlements "JitterbugTunnel/JitterbugTunnel.entitlements" --timestamp=none "Jitterbug.xcarchive/Products/Applications/Jitterbug.app/PlugIns/JitterbugTunnel.appex"
          codesign --force --sign - --entitlements "Jitterbug/Jitterbug.entitlements" --timestamp=none "Jitterbug.xcarchive/Products/Applications/Jitterbug.app"
      - name: Compress
        run: tar cf Jitterbug.xcarchive.tgz Jitterbug.xcarchive
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Jitterbug
          path: Jitterbug.xcarchive.tgz
  build-ios-lite:
    name: Jitterbug Lite
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: xcodebuild archive -archivePath JitterbugLite -scheme JitterbugLite -configuration Release CODE_SIGNING_ALLOWED=NO
      - name: Compress
        run: tar cf JitterbugLite.xcarchive.tgz JitterbugLite.xcarchive
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: JitterbugLite
          path: JitterbugLite.xcarchive.tgz
  build-macos-ui:
    name: Jitterbug (macOS)
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: xcodebuild archive -archivePath JitterbugMac -scheme JitterbugMac -configuration Release
      - name: Compress
        run: tar cf JitterbugMac.xcarchive.tgz JitterbugMac.xcarchive
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: JitterbugMac
          path: JitterbugMac.xcarchive.tgz
