name: Build
on:
  push:
    branches:
      - 'main'
      - 'dev'
    tags-ignore:
      - '**'
    paths-ignore:
      - 'LICENSE'
      - '**.md'
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      test_release:
        description: 'Test release?'
        required: true
        default: 'false'

jobs:
  build-ios:
    name: Jitterbug
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          xcodebuild archive -archivePath Jitterbug -scheme Jitterbug -configuration Release CODE_SIGNING_ALLOWED=NO
      - name: Compress
        run: tar cf Jitterbug.xcarchive.tgz Jitterbug.xcarchive
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Jitterbug
          path: Jitterbug.xcarchive.tgz
  build-ios-lite:
    name: Jitterbug Lite
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: xcodebuild archive -archivePath JitterbugLite -scheme JitterbugLite -configuration Release CODE_SIGNING_ALLOWED=NO
      - name: Compress
        run: tar cf JitterbugLite.xcarchive.tgz JitterbugLite.xcarchive
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: JitterbugLite
          path: JitterbugLite.xcarchive.tgz
